package jiyun.com.xiongmao.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiyun.com.xiongmao.beans.PingLun;

import jiyun.com.xiongmao.greendao.PingLunDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pingLunDaoConfig;

    private final PingLunDao pingLunDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pingLunDaoConfig = daoConfigMap.get(PingLunDao.class).clone();
        pingLunDaoConfig.initIdentityScope(type);

        pingLunDao = new PingLunDao(pingLunDaoConfig, this);

        registerDao(PingLun.class, pingLunDao);
    }
    
    public void clear() {
        pingLunDaoConfig.clearIdentityScope();
    }

    public PingLunDao getPingLunDao() {
        return pingLunDao;
    }

}
